<?php

namespace Cairn\UserBundle\Repository;

/**
 * AccountScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountScoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function whereConfirmed(QueryBuilder $ab)
     {
         $ab->andWhere('u.confirmationToken is NULL');
         return $this;
     }

}
