<?php

namespace Cairn\UserBundle\Repository;

/**
 * AppDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppDataRepository extends \Doctrine\ORM\EntityRepository
{
}
