<?php

namespace Cairn\UserBundle\Repository;

/**
 * BanknoteStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanknoteStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
