<?php

namespace Cairn\UserBundle\Repository;

use Cairn\UserBundle\Entity\BaseNotification;
use Cairn\UserBundle\Entity\NotificationData;

use Doctrine\ORM\QueryBuilder;                                                 

/**
 * BaseNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
