<?php

namespace Cairn\UserBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAvailableCardWithCode($code)
    {
        $cb = $this->createQueryBuilder('c');                  
        $cb->where('c.user is NULL')
            ->andWhere('c.code = :code')
            ->setParameter('code',$code)
            ->setMaxResults(1);

        $result = $cb->getQuery()->getOneOrNullResult();
        return $result;
    }

    public function findAvailableCards()
    {
        return $this->findBy(array('user'=>NULL));
    }

    public function whereAvailable(QueryBuilder $cb)
    {
        $cb->andWhere('c.user is NULL'); 
        return $this;
    }

    public function whereExpiresBefore(QueryBuilder $cb, $date)
    {
        $cb->andWhere('c.expirationDate <= :expirationDate')
           ->setParameter('expirationDate',$date); 
        return $this;
    }
}
