<?php

namespace Cairn\UserBundle\Repository;

/**
 * HelloassoConversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelloassoConversionRepository extends \Doctrine\ORM\EntityRepository
{
}
