<?php

namespace Cairn\UserBundle\Repository;

/**
 * MandateDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MandateDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
