<?php

namespace Cairn\UserBundle\Repository;

/**
 * MandateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MandateRepository extends \Doctrine\ORM\EntityRepository
{
    public function whereStatus(QueryBuilder $mb, $status)
    {
        $mb->andWhere('m.status = :status')
            ->setParameter('status',$status);
        return $this;
    }

    public function whereContractor(QueryBuilder $mb, $userID)
    {
        $mb->join('m.contractor','c')
            ->andWhere('c.id = :id')                                           
            ->setParameter('id',$userID);
        return $this;
    }

}
