<?php

namespace Cairn\UserBundle\Repository;

/**
 * NotificationPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationPermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
