<?php

namespace Cairn\UserBundle\Repository;

/**
 * OnlinePaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnlinePaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
