<?php

namespace Cairn\UserBundle\Repository;

use Cairn\UserBundle\Repository\PushNotificationRepository;
use Cairn\UserBundle\Entity\PushNotification;

use Doctrine\ORM\QueryBuilder;                                                 

/**
 * PaymentPushNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentPushNotificationRepository extends PushNotificationRepository
{
    public function getPaymentTokensAsArray(array $appDataIds = [], array $types = [], $amount)
    {
        if( empty($appDataIds) ){
            return [];
        }

        $pb = $this->createQueryBuilder('p');

        $pb->select('p.deviceToken');
        $this->whereAppDataIsIn($pb,$appDataIds)->whereKeyword($pb, PushNotification::KEYWORD_PAYMENT);

        $pb->andWhere('p.minAmount <= :amount')
            ->setParameter('amount',$amount);

        $this->whereTypes($pb,$types);
        return $pb->getQuery()->getResult("COLUMN_HYDRATOR");
    }

    public function whereTypes(QueryBuilder $pb, array $types)
    {
        $conditions = array();
        foreach($types as $type){
            $conditions[] = "p.types LIKE '%i:".$type.";%'";
        }

        $orX = $pb->expr()->orX();
        $orX->addMultiple($conditions);
        $pb->andWhere($orX);

        return $this;
    }
}
