<?php

namespace Cairn\UserBundle\Repository;

/**
 * ReconversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReconversionRepository extends \Doctrine\ORM\EntityRepository
{
}
