<?php

namespace Cairn\UserBundle\Repository;

/**
 * RegistrationNotificationPushRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationNotificationPushRepository extends \Doctrine\ORM\EntityRepository
{
}
