<?php

namespace Cairn\UserBundle\Repository;

/**
 * SmsDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsDataRepository extends \Doctrine\ORM\EntityRepository
{
}
