<?php

namespace Cairn\UserBundle\Repository;

use Cairn\UserBundle\Entity\Sms;
use Doctrine\ORM\QueryBuilder;                                                 

/**
 * SmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsRepository extends \Doctrine\ORM\EntityRepository
{

    public function whereState(QueryBuilder $sb, $state)
    {
        $sb->andWhere('s.state = :state')                                           
            ->setParameter('state',$state);
        return $this;

    }

    public function whereOlderThan(QueryBuilder $sb, $date)
    {
        $sb->andWhere('s.requestedAt < :date')
            ->setParameter('date',$date);
        return $this;

    }

}
