<?php

namespace Cairn\UserBundle\Repository;

/**
 * SmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsRepository extends \Doctrine\ORM\EntityRepository
{
}
