<?php

namespace Cairn\UserBundle\Repository;

use Doctrine\ORM\QueryBuilder;                                                 

/**
 * WebPushSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebPushSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSubsByWebEndpoints(array $endpoints, bool $selectRoot=false)
    {
        $wb = $this->createQueryBuilder('w');

        if($selectRoot){
            $wb->leftJoin('w.notificationData','n')->addSelect('n')->leftJoin('n.baseNotifications','b')->addSelect('b');
        }

        $this->whereWebEndpoints($wb,$endpoints);
        
        return $wb->getQuery()->getResult();
    }

    public function whereWebEndpoints(QueryBuilder $wb,$endpoints)
    {
        $wb->andWhere('w.endpoint IN (:endpoints)')
            ->setParameter('endpoints',$endpoints);

        return $this;
    }

}
