<?php

namespace Cairn\UserBundle\Repository;

/**
 * WebPushSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebPushSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
