<?php

namespace Cairn\UserBundle\Repository;

/**
 * ZipCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName(string $name)
    {
        $re = '/([0-9]{5})\s(.*)/';
        preg_match($re, $name, $matches, PREG_OFFSET_CAPTURE, 0);

        if (count($matches)==3){
            $cb = $this->createQueryBuilder('z');
            $cb->Where('z.zipCode = :code')
                ->andWhere('z.city = :city')
                ->setParameter('code',$matches[1][0])
                ->setParameter('city',$matches[2][0])
                ->setMaxResults(1);

            $result = $cb->getQuery()->getOneOrNullResult();
            return $result;
        }

        return null;
    }

    public function findCorrectZipCity($zipCode,$city)
    {
             $zip = $this->findOneBy(array('zipCode'=>$zipCode,'city'=> $city));
             if(! $zip){
                 $zipCities = $this->findByZipCode($zipCode);
                 if(count($zipCities) == 0){
                     return NULL;
                 }
 
                 $zip = $zipCities[0]; 
                 $resScore = similar_text($city,$zip->getCity(),$resPerc);
                 foreach($zipCities as $zc){
                     $probaScore = similar_text($city,$zc->getCity(),$probaPerc);
                     if($probaPerc > $resPerc){
                         $zip = $zc;
                         $resPerc = $probaPerc;
                     }
                 }
             }
             return $zip;

    }

}
