<?php

namespace Cairn\UserBundle\Repository;

/**
 * ZipCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCityRepository extends \Doctrine\ORM\EntityRepository
{
}
