FROM nginx:latest

LABEL description="CairnB2B based on debian" \
        maintainer="mazda91 <https://github.com/mazda91>"

COPY nginx.conf /etc/nginx/nginx.conf
COPY moncompte.conf /etc/nginx/conf.d/example.local.conf

EXPOSE 8000


