<?php

namespace Cairn\UserCyclosBundle\Repository;

/**
 * TransactionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
