<?php

namespace Proxies\__CG__\Cairn\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Card extends \Cairn\UserBundle\Entity\Card implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'id', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'number', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'fields', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'rows', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'cols', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'enabled', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'user', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'creationDate', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'generated'];
        }

        return ['__isInitialized__', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'id', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'number', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'fields', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'rows', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'cols', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'enabled', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'user', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'creationDate', '' . "\0" . 'Cairn\\UserBundle\\Entity\\Card' . "\0" . 'generated'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Card $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function generateCard($env)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateCard', [$env]);

        return parent::generateCard($env);
    }

    /**
     * {@inheritDoc}
     */
    public function setFields($fields)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFields', [$fields]);

        return parent::setFields($fields);
    }

    /**
     * {@inheritDoc}
     */
    public function getFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFields', []);

        return parent::getFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Cairn\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setRows($rows)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRows', [$rows]);

        return parent::setRows($rows);
    }

    /**
     * {@inheritDoc}
     */
    public function getRows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRows', []);

        return parent::getRows();
    }

    /**
     * {@inheritDoc}
     */
    public function setCols($cols)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCols', [$cols]);

        return parent::setCols($cols);
    }

    /**
     * {@inheritDoc}
     */
    public function getCols()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCols', []);

        return parent::getCols();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationDate', []);

        return parent::getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationDate($creationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationDate', [$creationDate]);

        return parent::setCreationDate($creationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenerated($generated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenerated', [$generated]);

        return parent::setGenerated($generated);
    }

    /**
     * {@inheritDoc}
     */
    public function isGenerated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isGenerated', []);

        return parent::isGenerated();
    }

}
